### ISSUE TITLE
Documentation required  for  specifying OpenFn "service user" account for creating tasks in Asana

### ISSUE THREAD

**Issue by jayesse** [OpenFn/language-asana#4]
It is important to have a service user account in OpenFn that is used to upsert tasks in Asana,
This service user must belong to the customer's organization in order to have full control over the asana project. 

The language-asana documentation needs to be updated to reflect the steps required, authentication process and API interactions needed to successfully execute the necessary operations. Please confirm how the [configuration parameters](https://github.com/OpenFn/language-asana#sample-configuration) can be retrieved from Asana. 

The documentation must be standardized to enable non-expert users to easily comprehend and successfully configure the job.

**Comment by aleksa-krolls** [comment]
fyi @jayesse added the line `Please confirm how the [configuration parameters](https://github.com/OpenFn/language-asana#sample-configuration) can be retrieved from Asana.`

**Comment by lakhassane** [comment]
@jayesse I added a section on how to create an access token. Let me know if it's helpful

**Comment by aleksa-krolls** [comment]
@lakhassane awesome, and confirming this is the right `configuration`? And apiVersion `1.0` is what should be used for now? 
https://github.com/OpenFn/language-asana#sample-configuration

**Comment by lakhassane** [comment]
Yes @aleksa-krolls correct.

We keep it in the configuration so that whenever there is a V2 only the credential will change

**Comment by aleksa-krolls** [comment]
@jayesse any other questions? Or can we close this issue?

**Comment by jayesse** [comment]
@aleksa-krolls We can close this issue. Many thanks.
