### ISSUE TITLE
Failed OpenFn Platform Jobs not showing detailed error messages in Run Logs

### ISSUE THREAD

**Issue by jayesse** [OpenFn/language-asana#5]
**Describe the bug**
Failed OpenFn Platform Jobs not showing error details in Run Logs.

I am troubleshooting an [Asana Upsert Job](https://openfn.org/projects/wcs-kobo-to-asana-staging/jobs/sKyUQi) for WCS and we are getting a 404 (Bad request, according to the [Asana API docs](https://developers.asana.com/docs/errors) ) error when the job fails. However, it is difficult to determine the cause of the failure, because the OpenFn platform does not print out the full error message.

**To Reproduce**
1. Log into OpenFn platform and navigate to this [Asana Upsert Job](https://openfn.org/projects/wcs-kobo-to-asana-staging/jobs/sKyUQi) .
2. Run the job and see the associated Run log. A sample failed run is available [here](https://openfn.org/projects/wcs-kobo-to-asana-staging/runs/0629f5e2-160d-70b2-bca7-8c481eb9f0bc)
3. The error shown does not contain precise details needed to pinpoint the problem(s).

**Expected behavior**
I expect to see the full error printout  to help narrow down the problem (Eg. The line(s) of code causing the error.

As a temporary remedy, you can printout the full error message and share with me to enable faster troubleshooting

**Screenshots**
![image](https://user-images.githubusercontent.com/97878823/172645356-956b2c26-01d7-4ed6-8ffe-baa06838f8a4.png)

**Additional context**
This job upserts kobo submissions into Asana. It uses `language-asana` adaptor version 2.0. 
There is a **similar WCS [upsert job](https://openfn.org/projects/wcs-kobo-to-asana-staging/jobs/Li36ED)** within the project, which uses the same adaptor and the same credentials and it runs successfully.

**Comment by aleksa-krolls** [comment]
@taylordowns2000 this is making it very hard for WCS developers to self-troubleshoot (as well as our team). Do you have time to check this out this week? Added to the top of the backlog. @jayesse can answer any questions.

**Comment by taylordowns2000** [comment]
@jayesse , @aleksa-krolls , I want to leave this issue open as an enhancement to language-asana, but I made a small change to the job so that you can see the [full text of those Asana errors](https://openfn.org/projects/wcs-kobo-to-asana-staging/runs/062a1d94-32cc-7a40-ad91-7e0a7b1ddb50) in the meantime.

The change is to wrap `upsertTask` in an `fn` block, so that you've got unlimited flexibility in terms of how it's called, how errors are handled, etc. We go from:
```js
upsertTask(...)
```
To:
```
fn(state =>
  upsertTask(...)(state)
  .catch(e => {
    console.log('Asana says', JSON.stringify(e.response.data, null, 2));
    throw e;
  })
);
```
It's verbose, but does the job nicely.

IMO, this _closes_ the related issue for the client, but I'd still like to leave this issue open over here for the future of the language package.

**Comment by aleksa-krolls** [comment]
thanks @taylordowns2000. Moving back to backlog to pick it back up whenever you have the time. 

@jayesse moving this back to backlog for TD to work this into the adaptor... pls create another issue on the consosci repo if you need anything else that's client-specific.

**Comment by taylordowns2000** [comment]
@jayesse , `v2.0.1` addresses this issue. please feel free to upgrade!

https://github.com/OpenFn/language-asana/releases/tag/v2.0.1

**Comment by jayesse** [comment]
Thanks @taylordowns2000
